sohyunPJT/sohyunSite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

sohyunPJT/sohyunSite/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rating/', views.create_rating, name='create_rating'),
    path('<int:movie_pk>/rating/<int:rating_pk>', views.delete_rating, name='delete_rating'),
    path('random_movie/', views.random_movie, name='random_movie'),
]

sohyunPJT/sohyunSite/sohyunSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

sohyunPJT/sohyunSite/movies/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

# movies.json파일을 참고했을 때,
# 위쪽 부분의 json파일 부분엔 genre만 모아둔 부분이 있고
# 해당 부분에 "model" : "movies.genre" 라고 적혀있었기 때문에 다음과 같이 작성
class Genre(models.Model):
    name = models.CharField(max_length=50)

# movies.json파일을 참고했을 때,
# 아래쪽 부분의 json파일 부분엔 genre만 모아둔 부분이 있고
# 해당 부분에 "model" : "movies.movie" 라고 적혀있었기 때문에 다음과 같이 작성
class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=200)
    score = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

    def username(self):
        return self.user.username

    def __str__(self):
        return f'{self.movie} | {self.score} | {self.comment}'

sohyunPJT/sohyunSite/movies/forms.py
from django import forms
from .models import Rating

class RatingForm(forms.ModelForm):
    
    class Meta:
        model = Rating
        # fields = '__all__'
        exclude = ['movie', 'user']

sohyunPJT/sohyunSite/movies/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Movie, Rating
from django.views.decorators.http import require_GET, require_POST
from .forms import RatingForm
import random


# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie,pk=movie_pk)
    ratings = movie.rating_set.all()
    user_ids = list(Rating.objects.filter(movie=movie).values_list('user__id', flat=True))
    rating_form = RatingForm()
    context = {
        'movie' : movie,
        'user_ids': user_ids,
        'ratings': ratings,
        'rating_form': rating_form,
    }
    return render(request, 'movies/detail.html', context)

@require_POST
def create_rating(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    rating_form = RatingForm(request.POST)
    if rating_form.is_valid():
        rating = rating_form.save(commit=False)
        rating.movie = movie
        rating.user = request.user
        rating.save()
        return redirect('movies:detail', movie.pk)
    context = {
        'rating_form': rating_form,
        'movie': movie,
        'ratings': movie.rating_set.all(),
    }
    return render(request, 'movies/detail.html', context)

@require_POST
def delete_rating(request, movie_pk, rating_pk):
    if request.user.is_authenticated:
        rating = get_object_or_404(Rating, pk=rating_pk)
        if request.user == rating.user:
            rating.delete()
    return redirect('movies:detail', movie_pk)

def random_movie(request):
    num = random.randint(1, 100)
    movie = get_object_or_404(Movie, pk=num)
    ratings = movie.rating_set.all()
    rating_form = RatingForm()
    context = {
        'movie': movie,
        'ratings': ratings,
        'rating_form': rating_form,
    }
    return render(request, 'movies/detail.html', context)

sohyunPJT/sohyunSite/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ movie.title }}</h1>
    <p>
      {% for genre in movie.genres.all %}
      {{ genre.name }}
      {% endfor %}
    </p>

    <hr>

    <p>popularity : {{ movie.popularity }}</p>

    <hr>

    <p>vote average : {{ movie.vote_average }}</p>

    <hr>

    <p>overview : {{ movie.overview }}</p>

    <hr>

    <img src="{{ movie.poster_path }}" alt="">

  <hr>

  <!--댓글 및 점수주기-->

  <div class="container">
  {% for rating in ratings %}
    <li>
      {{ rating.user }} / {{ rating.score }}점 - {{ rating.comment }} - {{ rating.created_at }}
      {% if request.user == rating.user %}
        <form action="{% url 'movies:delete_rating' movie.pk rating.pk %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    </li>
  {% empty %}
    <p>아직 작성된 평점이 없습니다.</p>
  {% endfor %}
  
  <br>
  {% if request.user.id in user_ids %}
    <strong>이미 평점을 등록한 영화입니다.</strong>
  {% else %}
    {% if request.user.is_authenticated %}
      <div class="text-center"><strong>1~5점까지 평점을 남겨주세요.</strong></div><br>
      <form action="{% url 'movies:create_rating' movie.pk %}" method="POST">
        {% csrf_token %}
        {{ rating_form }}
        <input class="btn btn-success" type="submit">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}" class="btn btn-dark">[평점을 남기시려면 로그인하세요.]</a>
    {% endif %}
  {% endif %}
  </div>
  <div class="container d-flex flex-row-reverse">
    <a class="btn btn-primary" role="button" href="{% url 'movies:index' %}">뒤로가기</a>
  </div>
  
{% endblock content %}

sohyunPJT/sohyunSite/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
      <br>
      <hr>
      <br>
      <!--bootstrap card code start-->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        {% for movie in movies %}
          <div class="col">
            <div class="card h-100 text-white bg-dark">
              <a href="{% url 'movies:detail' movie.pk %}"><img src="{{ movie.poster_path }}" class="card-img-top" alt="..."></a>
              <div class="card-body text-center">
                {{ movie.title }}
              </div>
            </div>
          </div>
          <!--bootstrap card code end-->
        {% endfor %}
      </div>
  </div>
{% endblock content %}