sohyunPJT/sohyunSite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

sohyunPJT/sohyunSite/community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # 좋아요 기능
    path('<int:review_pk>/like/', views.like, name='like'),
]

sohyunPJT/sohyunSite/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rating/', views.create_rating, name='create_rating'),
    path('<int:movie_pk>/rating/<int:rating_pk>', views.delete_rating, name='delete_rating'),
    path('random_movie/', views.random_movie, name='random_movie'),
]

sohyunPJT/sohyunSite/sohyunSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

sohyunPJT/sohyunSite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField('self', symmetrical=False, related_name='followings')

sohyunPJT/sohyunSite/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 리뷰에 대한 좋아요 기능 추가
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

class Comment(models.Model):
    # 댓글의 내용
    content = models.CharField(max_length=200)
    # Review 모델 클래스의 id를 가져오기 위해 설정
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # auth 유저의 id를 가져오기 위해 설정
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

sohyunPJT/sohyunSite/movies/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

# movies.json파일을 참고했을 때,
# 위쪽 부분의 json파일 부분엔 genre만 모아둔 부분이 있고
# 해당 부분에 "model" : "movies.genre" 라고 적혀있었기 때문에 다음과 같이 작성
class Genre(models.Model):
    name = models.CharField(max_length=50)

# movies.json파일을 참고했을 때,
# 아래쪽 부분의 json파일 부분엔 genre만 모아둔 부분이 있고
# 해당 부분에 "model" : "movies.movie" 라고 적혀있었기 때문에 다음과 같이 작성
class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=200)
    score = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

    def username(self):
        return self.user.username

    def __str__(self):
        return f'{self.movie} | {self.score} | {self.comment}'

sohyunPJT/sohyunSite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

sohyunPJT/sohyunSite/accounts/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm


@require_http_methods(['GET', 'POST'])
def signup(request):
    # 로그인된 사용자라면,
    if request.user.is_authenticated:
        # community 앱의 index.html로 보낸다.
        return redirect('movies:index')
    # 로그인 안된 사용자라면 
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # 유효하다면, 세션 CREATE
            # views.py와 아래이름이 signup으로 같으면 안되기 때문에 아래를 바꿔준다
            # import부분도 as로 바꿔주자
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    # 로그인된 사용자라면,
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        # ModelForm이 아닌 Form 이기 때문에 
        # AuthenticationForm은 첫 번재 인자를 request로 받는다.
        # 요청 request , 데이터 request.POST  
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # 유효하다면, 세션 CREATE
            # views.py와 아래이름이 login으로 같으면 안되기 때문에 아래를 바꿔준다
            # import부분도 as로 바꿔주자
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
     # 현재 request에 대한 db의 session data를 완전히 정리하고, 
    # 클라이언트 쿠키에서도 session id가 삭제된다.
    auth_logout(request)
    return redirect('movies:index')

@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                followed = False
            else:
                person.followers.add(user)
                followed = True
        followed_status = {
            'followed': followed,
            'followers_count': person.followers.count(),
            'followings_count': user.followers.count(), 
        }
        return JsonResponse(followed_status)
    return redirect('accounts:profile', person.username)

sohyunPJT/sohyunSite/accounts/templates/accounts/follow.html
<div class="container jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ person.username }}</h1>
  <hr>
  {% with followings=person.followings.all followers=person.followers.all %}
    <p class="lead">
      팔로잉 : 
      <span id='followings-count-{{ person.pk }}'>{{ followings|length }}</span>
       / 팔로워 :
       <span id='followers-count-{{ person.pk }}'>{{ followers|length }}</span>       
    </p>
      
    <!-- 팔로우 버튼 -->
    {% if request.user != person %}
      <form id="follow-form" data-user-id="{{ person.pk }}">
        {% csrf_token %}
        {% if request.user in followers %}
          <button class='btn btn-link btn-outline-light' role="button">
          <i id='follow-{{ person.pk }}' class='fas fa-hand-pointer' style='color: blue'></i>
          </button>
        {% else %}
          <button class='btn btn-link btn-outline-light' role="button">
          <i id='follow-{{ person.pk }}' class='fas fa-hand-pointer' style='color: gray'></i>
          </button>
        {% endif %}
      </form>
    {% endif %}
    
  {% endwith %}
</div>

sohyunPJT/sohyunSite/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Hi, I'm login.html</h1>
<h1>로그인 폼</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock  %}

sohyunPJT/sohyunSite/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">{{ person.username }}님의 프로필</h1>

{% include 'accounts/follow.html' %}

<div class="container">

<!--Bootstrap Accordion Component Start-->
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        <strong>{{ person.username }}의 평점</strong>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
        <ul>
          {% for rating in person.rating_set.all %}
            <li>
              {{ rating.movie.title }} - {{ rating.score }}점
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        <strong>{{ person.username }}가 쓴 글</strong>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
        <ul>
          {% for review in person.review_set.all %}
            <li>
              {{ review.title }}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        <strong>{{ person.username }}가 쓴 댓글</strong>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        <ul>
          {% for comment in person.comment_set.all %}
            <li>
              {{ comment.content }}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
        <strong>{{ person.username }}가 좋아요한 글</strong>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingFour">
      <div class="accordion-body">
        <ul>
          {% for review in person.like_reviews.all %}
            <li>
              {{ review.title }} - {{ review.content }}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
<!--Bootstrap Accordion Component end-->
<hr>
</div>
<div class="container d-flex flex-row-reverse">
  <a class="btn btn-primary" role="button" href="{% url 'community:index' %}">뒤로가기</a>
</div>

<!-- JS start -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  form.addEventListener('submit', function (event) {
    event.preventDefault()
    console.log(event)
    const userId = event.target.dataset.userId

    axios({
      method: 'post',
      url: `/accounts/follow/${userId}/`,
      headers: {'X-CSRFToken': csrftoken},
      }).then((response) => {
      const followed = response.data.followed
      const followersCount = response.data.followers_count
      const followingsCount = response.data.followings_count
      
      const followButton = document.querySelector(`#follow-${userId}`)
      if (followed) {
        followButton.style.color = 'blue'
      } else {
        followButton.style.color = 'gray'
      }
      
      const followingsNum = document.querySelector(`#followings-count-${userId}`)
      followingsNum.innerText = followingsCount
      const followersNum = document.querySelector(`#followers-count-${userId}`)
      followersNum.innerText = followersCount
      
    })
  })
</script>
<!-- JS end -->

{% endblock  %}

sohyunPJT/sohyunSite/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Hi, I'm signup.html</h1>
<h3>회원가입 폼</h3>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock  %}