sohyunPJT/sohyunSite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

sohyunPJT/sohyunSite/community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # 좋아요 기능
    path('<int:review_pk>/like/', views.like, name='like'),
]

sohyunPJT/sohyunSite/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rating/', views.create_rating, name='create_rating'),
    path('<int:movie_pk>/rating/<int:rating_pk>', views.delete_rating, name='delete_rating'),
    path('random_movie/', views.random_movie, name='random_movie'),
]

sohyunPJT/sohyunSite/sohyunSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

sohyunPJT/sohyunSite/sohyunSite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--bootstrap CSS CDN start-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!--bootstrap CSS CDN end-->
  <!-- fontawesome start -->
  <script src="https://kit.fontawesome.com/dacf7dcd9c.js" crossorigin="anonymous"></script>
  <!-- fontawesome end-->
  <title>Document</title>
</head>
<body>
  <!--bootstrap navbar code start -->

  <!--스크롤을 내려도 항상 상단에 붙어있는 navbar로 만들어 줌-->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top shadow-lg rounded">

    <!--다양한 메뉴를 li tag로 만들어 ul tag안에 집어넣어서 정리해주었다.-->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'movies:index' %}">
            <!--fontawesome emoji start-->
            <i class="fas fa-video"></i>
            <!--fontawesome emoji end-->
            영화리스트</a>
          </li>
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'community:index' %}">
        <!--fontawesome emoji start-->
        <i class="fas fa-comments"></i>
        <!--fontawesome emoji end-->
        커뮤니티
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' request.user.username %}">
          <i class="fas fa-user-circle"></i> 프로필
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'movies:random_movie' %}">
            <i class="fas fa-question-circle"></i> 랜덤추천
            </a>
          </li>
          <li class="nav-item">
            <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-warning" type="submit" value="로그아웃">
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">
            <!--fontawesome emoji start-->
            <i class="fas fa-user-plus"></i>
            <!--fontawesome emoji end-->
            회원가입
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active btn btn-info" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!--bootstrap navbar code end -->


  {% block content %}
  
  {% endblock content %}

<!-- Footer start -->
<footer class="bg-dark text-white text-center mt-5">

  <!-- Grid container start-->
  <div class="container p-4">

    <!-- Section: Social media start-->
    <section class="mb-4">

      <!-- Facebook -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998" href="https://www.facebook.com" role="button"><i class="fab fa-facebook-f"></i></a>

      <!-- Instagram -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="https://www.instagram.com" role="button"><i class="fab fa-instagram"></i></a>

      <!-- Github -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #333333" href="https://github.com/" role="button"><i class="fab fa-github"></i></a>
    </section>
    <!-- Section: Social media end-->

    <section class="mb-4">
      <p>
        Made by 김대호 & 박소현 at SSAFY. 
      </p>
    </section>    

  </div>
  <!-- Grid container end-->

  <!-- Copyright start -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2021
    <a class="text-white" href="https://www.ssafy.com/">Samsung Software Academy For Youth</a>
  </div>
  <!-- Copyright end -->

</footer>
<!-- Footer end -->

 <!--bootstrap JS CDN start--> 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script> 
  <!--bootstrap JS CDN end--> 
</body>
</html>