sohyunPJT/sohyunSite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

sohyunPJT/sohyunSite/community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    # 좋아요 기능
    path('<int:review_pk>/like/', views.like, name='like'),
]

sohyunPJT/sohyunSite/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/rating/', views.create_rating, name='create_rating'),
    path('<int:movie_pk>/rating/<int:rating_pk>', views.delete_rating, name='delete_rating'),
    path('random_movie/', views.random_movie, name='random_movie'),
]

sohyunPJT/sohyunSite/sohyunSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

sohyunPJT/sohyunSite/community/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 리뷰에 대한 좋아요 기능 추가
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

class Comment(models.Model):
    # 댓글의 내용
    content = models.CharField(max_length=200)
    # Review 모델 클래스의 id를 가져오기 위해 설정
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # auth 유저의 id를 가져오기 위해 설정
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

sohyunPJT/sohyunSite/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user']

sohyunPJT/sohyunSite/community/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import JsonResponse
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


@require_GET
def index(request):
    if request.user.is_authenticated:
        reviews = Review.objects.order_by('-pk')
        context = {
            'reviews': reviews,
        }
        return render(request, 'community/index.html', context)
    else:
        return redirect('accounts:login')


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST) 
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)

@require_POST
def delete(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect('community:index')
    return redirect('community:detail', review.pk)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('community:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('community:index')
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'community/update.html', context)

@require_GET
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,
    }

    return render(request, 'community/detail.html', context)


@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('community:detail', review.pk)

    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }

    return render(request, 'community/detail.html', context)

@require_POST
def delete_comment(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('community:detail', review_pk)

@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            liked = False
        else:
            review.like_users.add(user)
            liked = True
        like_status = {
            'liked': liked,
            'count': review.like_users.count(),
        }
        return JsonResponse(like_status)
        # return redirect('community:index')
    return redirect('accounts:login')

sohyunPJT/sohyunSite/community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
<h1>Hi, I'm create.html from community app</h1>
  <h3 class="text-center">CREATE 폼</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock %}

sohyunPJT/sohyunSite/community/templates/community/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Hi, I'm detail.html from community</h1>
  <h3>DETAIL 폼</h3>
  <br>
  <h3>{{ review.pk }} 번째 글</h3>
  <hr>
  <p>제목: {{ review.title }}</p>
  <p>영화 제목: {{ review.movie_title }}</p>
  <p>내용: {{ review.content }}</p>
  <p>평점: {{ review.rank }}</p>
  <p>작성 시각: {{ review.created_at }}</p>
  <p>수정 시각: {{ review.updated_at }}</p>
  {% if request.user == review.user %}
    <a href="{% url 'community:update' review.pk %}" class="btn btn-primary">[UPDATE]</a>
    <form action="{% url 'community:delete' review.pk %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-danger">DELETE</button>
    </form>
  {% endif %}
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
      {{ comment.user }} - {{ comment.content }} - {{ comment.created_at }}
      {% if request.user == comment.user %}
        <form action="{% url 'community:delete_comment' review.pk comment.pk %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input class="btn btn-warning" type="submit" value="DELETE">
        </form>
      {% endif %}
    </div>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input class="btn btn-info" type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a class="btn btn-primary" href="{% url 'community:index' %}">[뒤로가기]</a>
{% endblock  %}

sohyunPJT/sohyunSite/community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h3>Community</h3>
  {% if user.is_authenticated %}
    <a class="btn btn-dark text-white" href="{% url 'community:create' %}">새 글 작성하기</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
  {% endif %}

  <hr>

  {% for review in reviews %}
    <p><b>작성자 : <a class="btn btn-dark text-white" href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></b></p>
    <p>영화 제목: {{ review.movie_title }}</p>
    <p>글 제목: {{ review.title }}</p>
    <!-- 좋아요 기능 start -->
    <form class="like_form" data-id='{{ review.pk }}'>
      {% csrf_token %}
      {% if user in review.like_users.all %}
        <button class="btn btn-link">
          <i id="like-{{ review.pk }}" class="fas fa-heart fa-lg" style="color:crimson;"></i>
        </button>
      {% else %}
        <button class="btn btn-link">
          <i id="like-{{ review.pk }}" class="fas fa-heart fa-lg" style="color:black;"></i>
        </button>
      {% endif %}
    </form>
    <p>
    <span id="like-count-{{ review.pk }}">{{ review.like_users.all|length }}</span>명이 이 글을 좋아합니다.
    </p>
    <a class="btn btn-primary" href="{% url 'community:detail' review.pk %}">[살펴보기]</a>
    <hr>
  {% endfor %}
    <!-- 좋아요 기능 end -->


  <!-- 좋아요를 하트모양으로 바꿔줄 JS start -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const forms = document.querySelectorAll('.like_form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    forms.forEach(function (form) {
      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const reviewId = event.target.dataset.id
  
        axios.post(`http://127.0.0.1:8000/community/${reviewId}/like/`, {},
        {headers: {'X-CSRFToken': csrftoken}
        }).then(function (response) {
          const liked = response.data.liked
          const count = response.data.count

          const likeButton = document.querySelector(`#like-${reviewId}`)
          if (liked) {
            likeButton.style.color = 'crimson'
          } else {
            likeButton.style.color = 'black'
          }
          const likeCount = document.querySelector(`#like-count-${reviewId}`)
          likeCount.innerText = `${count}`
        })
      })
    })
  </script>
  <!-- 좋아요를 하트모양으로 바꿔줄 JS end -->

{% endblock %}

sohyunPJT/sohyunSite/community/templates/community/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hi, I'm update.html from community</h1>
  <h3>UPDATE 폼</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-info" type="submit">
  </form>
  <hr>
  <a class="btn btn-primary" href="{% url 'community:detail' review.pk %}">[뒤로가기]</a>
{% endblock %}